version: '3'

services:
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    command: mongod --noauth --smallfiles
    networks:
      - webappnetwork
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    depends_on:
      - mongo
    ports:
      - '5000:5000'
    networks:
      - webappnetwork
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - '3000:3000'
    links:
      - api
    networks:
      - webappnetwork
networks:
  webappnetwork:
    driver: bridge
    # nginx:
  #   restart: always
  #   build:
  #     dockerfile: Dockerfile.dev
  #     context: ./nginx
  #   ports:
  #     - '3050:80'
