version: '3'

services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - 4005:80
  mongo:
    container_name: mongo
    image: 'mongo:latest'
    ports:
      - '27017:27017'
  redis:
    image: 'redis:latest'
  api:
    container_name: dev-connector
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    links:
      - mongo
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
