version: '2.4'

services:
  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - '80:80'
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: redis:alpine
    healthcheck:
      test: redis-cli ping

  mongo:
    image: mongo
    healthcheck:
      test: echo 'db.stats().ok' | mongo localhost:27017/devnetwork --quiet

  api:
    build:
      context: ./server
      target: dev
    volumes:
      - ./server:/app
    environment:
      # - MONGO_URI=
      - NODE_ENV=development
      # - REDIS_HOST=redis
      # - REDIS_PORT=6379
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy

  client:
    build:
      context: ./client
      target: dev
    environment:
      - NODE_ENV=development
    volumes:
      - ./client:/app
    depends_on:
      redis:
        condition: service_healthy

volumes:
  mongo-data:
